# Build tools Dockerfile
image: quay.io/pantheon-public/build-tools-ci:6.x

# Default Variables
variables:
  CI_BUILD_NUMBER: $CI_PIPELINE_IID
  DEFAULT_SITE: $CI_PROJECT_NAME
  PR_NUMBER: $CI_MERGE_REQUEST_IID
  CI_BRANCH: $CI_COMMIT_REF_NAME

# Cache libraries in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - web/themes/custom/example_theme/node_modules
    - /composer/cache
    - $HOME/.composer/cache

stages:
  - build

before_script:
  - export PATH="$PATH:$CI_PROJECT_DIR/.ci/scripts"
  - export BASH_ENV="$HOME/.envvarsrc"
  - /build-tools-ci/scripts/set-environment
  - source $BASH_ENV
  # See https://docs.gitlab.com/ee/ci/ssh_keys/README.html
  - eval $(ssh-agent -s) && ssh-add <(echo "$SSH_PRIVATE_KEY")
  - terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

deploy:
  stage: build
  environment:
    name: deploy/$TERMINUS_ENV
    url: https://$TERMINUS_ENV-$TERMINUS_SITE.pantheonsite.io/
  script:
    - echo "Target site.env is $TERMINUS_SITE.$TERMINUS_ENV"
    - 01-prepare
    - composer -n build-assets
    - npm install
    - 02-deploy
  only:
    - merge_requests
    - master
